#######################################################################
# Copyright (C) 2017 Kaloyan Raev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################
language: java

env:
  global:
  - JAVA_LIBSTORJ_VERSION=0.8.1

install: true

script: mvn clean verify

before_deploy:
- mvn package
# Prepare a package for Windows
- curl -sSL https://github.com/Storj/java-libstorj/releases/download/$JAVA_LIBSTORJ_VERSION/java-libstorj-$JAVA_LIBSTORJ_VERSION-win64-dlls.zip -O
- unzip -f java-libstorj-$JAVA_LIBSTORJ_VERSION-win64-dlls.zip
- zip -j goobox-sync-storj-$TRAVIS_TAG-win64.zip java-libstorj-dlls-$JAVA_LIBSTORJ_VERSION/* src/main/resources/goobox-sync-storj.bat target/goobox-sync-storj-$TRAVIS_TAG.jar
# Prepare a package for macOS
- mkdir -p java-libstorj-$JAVA_LIBSTORJ_VERSION-mac-dylibs
- curl -sSL https://github.com/Storj/java-libstorj/releases/download/$JAVA_LIBSTORJ_VERSION/java-libstorj-$JAVA_LIBSTORJ_VERSION-macos-dylibs.tar.gz | tar -zxv -C java-libstorj-$JAVA_LIBSTORJ_VERSION-mac-dylibs
- zip -j goobox-sync-storj-$TRAVIS_TAG-darwin.zip java-libstorj-$JAVA_LIBSTORJ_VERSION-mac-dylibs/* src/main/resources/goobox-sync-storj target/goobox-sync-storj-$TRAVIS_TAG.jar

deploy:
  provider: releases
  api_key:
    secure: Dfmu/r1c2QwZLit0qRl4enMHWlTBdjbR90F/NDPrSvKJngDjW1Sg8oQQvOUxJWBabjwHhs24NWsaFF114+2nZKqlAo4KMyW0jhmOGWAg0avhyYbEAkbtXoRsmZTyk+7lQf0VDzOZNcRROARBiEZjwEMqhNS5I/g0SY8Y6osnRXi5D+hoSos2TQpKt0JBExUeqf1861YIos82fEgSrLylNGDYfpJwIQ56Wza01PwXle9ZEWmZWV/byheHbfVAmmaCWpz/8/8Iw78+m5UuMyEFmeC0J1QbRrNt2cM/vAcLqZEBHISUj8Vl4oNyNnl0g0GlTQZKIKibG+yH8dsy0VXR95RomSAZBxnwmLQAnSRpKVTmxvI3rIgamqM7o0IrsMnQ2U1SnO2vepXhawwIAC5LlOEijuhcUN9CRD2a8EGJ7nXgHuZ45n7F02hl8mgNIlT/fWiNIAByl2RT4eID+1jLgtyoVuc6GmIQZQ5Reop0LdWn96AHhsKg00yUW+t5K6yzJUl2RN42iZl5mw1iE99/aDJBcBN8NqzX0uonRXA9orovOuNcKnHs56VH4iOEhBwySkUjlFvm0myQJnrK+P259pCtiy3VnG5WJ1Pkp8/2/YhQWzXSxVWiKMN/0EPXWcfjh8WaxhdsZQoeozi0u8P6rkPzg9ucftJu6OFttxhdZG8=
  skip_cleanup: true
  file:
  - goobox-sync-storj-$TRAVIS_TAG-win64.zip
  - goobox-sync-storj-$TRAVIS_TAG-darwin.zip
  on:
    tags: true
    repo: kaloyan-raev/goobox-sync-storj
