#######################################################################
# Copyright (C) 2017 Kaloyan Raev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################
language: java

env:
  global:
  - JAVA_LIBSTORJ_VERSION=0.8.1

install: true

script: mvn clean verify

before_deploy:
- mvn package
# Prepare a package for Windows
- curl -sSL https://github.com/Storj/java-libstorj/releases/download/$JAVA_LIBSTORJ_VERSION/java-libstorj-$JAVA_LIBSTORJ_VERSION-win64-dlls.zip -O
- unzip -f java-libstorj-$JAVA_LIBSTORJ_VERSION-win64-dlls.zip
- zip -j goobox-sync-storj-$TRAVIS_TAG-win64.zip java-libstorj-dlls-$JAVA_LIBSTORJ_VERSION/* src/main/resources/goobox-sync-storj.bat target/goobox-sync-storj-$TRAVIS_TAG.jar
# Prepare a package for macOS
- mkdir -p java-libstorj-$JAVA_LIBSTORJ_VERSION-mac-dylibs
- curl -sSL https://github.com/Storj/java-libstorj/releases/download/$JAVA_LIBSTORJ_VERSION/java-libstorj-$JAVA_LIBSTORJ_VERSION-macos-dylibs.tar.gz | tar -zxv -C java-libstorj-$JAVA_LIBSTORJ_VERSION-mac-dylibs
- unzip -f java-libstorj-$JAVA_LIBSTORJ_VERSION-mac-dylibs.zip
- zip -j goobox-sync-storj-$TRAVIS_TAG-darwin.zip java-libstorj-$JAVA_LIBSTORJ_VERSION-mac-dylibs/* src/main/resources/goobox-sync-storj target/goobox-sync-storj-$TRAVIS_TAG.jar

deploy:
  provider: releases
  api_key:
    secure: BFNGvCiVL/G9yAM5b7rqlicCttonF2E84jNVG4SIfNj08DgeIP0w/v8XTwHvCP9/Frt0+1X9GM3BY1VmBLxe7I5lLOd2E7fz28p+DAZL35yLqrEYTbzwb6/mFxVyOnUM3vjIbH0/Jnf5uCXwzG8gYvhZQBDG2GMmx6C/BqDfEB3yFCG3GKwVi9BhzR7kL123pfa+ZwC2n0zh7Rmslu2uwhxJ+jxSAUofO9VWyBhSmxIc6JxJV1hxQPnwzZh4zTh5kmzVhjh8YCPABeNueL1Kzo6G+4Yp8K6FnxltsbzBruqk9kFxKes/9xwDT6Ym6HNRf+Zy0fE/s1mKiJ1N8+HamvFE8v7mUCuIn3wPNcpP2ytg0kB0auPRHcxaQwth3So9ys+yKv4P1Mg/DeyxkIiS2M02wj4lQqENsIOfNchDP/qMMQ06ePjBh5bLqy91Rcu7SQAx/uMxVMdTyv5cJAAueV0fMyrjt+feCnZvwK9/jA2xktFcyKeBLYaeaS5sX8kZjK2i1KBsDLTPlPd+R5B+xyja/FKJy8OkEGhSYWPhB6vgRRmoyvy+qTwqnegvwp8xc86dHKAZmzofE5u4Eq+suklOi0F3ejCUT/a7rzlgNVxg4+GcWeSYtDjLnp8ITo3QsACTW7SzbvZ5yIealdJMro+LWCYb7HLhkOBjYy1Gymo=
  skip_cleanup: true
  file:
  - goobox-sync-storj-$TRAVIS_TAG-win64.zip
  - goobox-sync-storj-$TRAVIS_TAG-darwin.zip
  on:
    tags: true
    repo: kaloyan-raev/goobox-sync-storj
